# Generated by Django 4.1.9 on 2023-07-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("species", models.CharField(max_length=75)),
                ("description", models.TextField(max_length=200)),
                ("rarity", models.CharField(max_length=15)),
                ("location", models.TextField(max_length=200)),
                ("fun_fact", models.TextField(max_length=200)),
            ],
        ),
    ]
